In [ ]:
#ques1 Arrays
import numpy

def arrays(arr):
  arr1=numpy.array(arr,float)
  return arr1[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
#ques2 Shape and reshape
import numpy as np
list = input().split(' ')
arr1=np.array(list,int)
print(np.reshape(arr1,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#ques 3 Transpose and Flatten
import numpy
N,M = map(int, input().split())
A=[]
for _ in range(N):
    A.append(input().split())
arrA = numpy.array(A,int)
print(numpy.transpose(arrA))
print(arrA.flatten())


2 2
1 2 
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
#ques 4 Concatenate
import numpy as np
n,m,p=map(int,input().split())
a1=np.array([input().split() for i in range(n)],int)
a2=np.array([input().split() for i in range(m)],int)
print (np.concatenate((a1,a2),axis=0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
#ques 5 Zeros and ones
import numpy as np
n=list(map(int,input().split()))
print(np.zeros(n, dtype=np.int))
print(np.ones(n, dtype=np.int))

3 3 3


TypeError: ignored

In [ ]:
#ques6 Eye and Identity
import numpy as np
n, m = map(int, input().split(' '))
print (np.eye(n, m, k = 0))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#ques7 Floor, ceil and rint
import numpy as np
np.set_printoptions(legacy='1.13')
A=input().split()
Arr=np.array(A,float)
print(np.floor(Arr))
print(np.ceil(Arr))
print(np.rint(Arr))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
#queS8 SUM AND PROD
import numpy as np
n,m=map(int, input().split())
A=[]
for _ in range(n):
    val=input().split()
    A.append(val)

Arr=np.array(A,int)
sumArr=np.sum(Arr, axis = 0)
print(np.prod(sumArr))

2 2
1 3
4 2
25


In [ ]:
#ques9 Max and Min
import numpy as np
n,m=map(int,input().split())
a=[]
for _  in range(n):
    val=input().split()
    a.append(val)

arr=np.array(a,int)
print(np.max(np.min(arr,axis=1)))



4 2
3 5 
3 7
1 3 
4 0
3


In [ ]:
#ques10 Mean, Var, std
import numpy as np
n,m=map(int,input().split())
a=[]
for _  in range(n):
    val=input().split()
    a.append(val)

arr=np.array(a,int)
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
print(round(np.std(arr, axis = None),11))

2 2 
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [ ]:
#ques11 Dot and cross
import numpy as np
n=int(input())
A=[]
B=[]
for _ in range(n):
    valA=input().split()
    A.append(valA)
for _ in range(n):
    valB=input().split()
    B.append(valB)
arrA=np.array(A,int)
arrB=np.array(B,int)
print(np.dot(arrA,arrB))



2
1 2 
3 4 
1 2
3 4
[[ 7 10]
 [15 22]]


In [1]:
#ques12 Inner and outer
import numpy as np
A=input().split()
B=input().split()
arrA=np.array(A,int)
arrB=np.array(B,int)
print(np.inner(arrA, arrB))
print(np.outer(arrA, arrB))

0 1
2 3
3
[[0 0]
 [2 3]]


In [2]:
#ques13 Polynomials
import numpy as np
A = list(map(float,input().split()));
x=int(input())
print(np.polyval(A,x))

1.1 2 3
0
3.0


In [3]:
#ques14 Linear Algebra
import numpy as np
n=int(input())
A=[]
for i in range(n):
    val=input().split()
    A.append(val)
arrA=np.array(A,float)
print(np.linalg.det(arrA))

2
1.1 1.1
1.1 1.1
0.0
